### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by 124399839** [wenguanwang/AGS#1]
非常感谢您的工作，发现您在百度网盘的model和数据已经不见了，可以在再上传一下吗，谢谢。

`Our model, segmentation and saliency results, and fixation data can also be found at Baidu Pan https://pan.baidu.com/s/1hz6iVOAMW3QRORebK3mC3Q , extaction code: 6prn`

**Comment by wenguanwang** [comment]
@124399839 感谢关注。我check了一下发现还在呀。
