### ISSUE TITLE
多目标

### ISSUE THREAD

**Issue by nationalflag** [wenguanwang/AGS#2]
请问这个算法适用有多个运动目标的情况吗？

**Comment by wenguanwang** [comment]
@nationalflag 请问多个目标的情况是指？

**Comment by nationalflag** [comment]
就是同一时刻有多个物体在动

**Comment by wenguanwang** [comment]
@nationalflag 可以handle最明显的多个前景物体。我们主要object-level video object segmentation的setting (DAVIS16, Youtube-Object, FBMS)。对于DAVIS17和Youtube-VOS这种提供instance-level标注的setting我们没有跑实验，但是也可以handle这种情况，不过需要进一步修改算法。
