### ISSUE TITLE
Results on DAVIS2017

### ISSUE THREAD

**Issue by wangbo-zhao** [wenguanwang/AGS#4]
Perfect work!!! I notice that you have added the results on DAVIS2017. If it is possible, could you  talk about how you modify this model to adapt  instance-level object segmentation?

**Comment by wenguanwang** [comment]
Basically, we first apply mask-rcnn to generate category agnostic object proposals for each frame. The segmentation results of our model are then used to filter out those background proposals and obtain pixel-wise, instance-level video segmentation results for each frame. Finally, we use a similar strategy in "Premvos: Proposal-generation, refinement and merging for video object segmentation" to link the object instances across different frames.

Details will be added in the journal version.

**Comment by wangbo-zhao** [comment]
Thank you very much and I‘am looking forward to your journal.
